# Thread Group settings
threads=12
rampup=12
loops=-1
duration=30

# Connection settings
protocol=http
server=localhost
port=8080

# URL Parameters
token=518476755
user=-1355124193
config_id=3

# Limits and Timers
throughput=40.0
max_duration=880