# Thread Group settings
threads=500
rampup=500
loops=-1
duration=540

# Connection settings
protocol=http
server=localhost
port=8080

# URL Parameters
token=518476755
user=-1355124193
config_id=3

# Limits and Timers
throughput=10000
max_duration=880