mainpage = https://www.tutu.ru/

xpath.hotelButton = //*[@id="__next"]/div[2]/div/div/div[2]/div[2]/button[1]

xpath.calendar = //input[contains(@data-ti, 'trip-date')]
xpath.hotelWhereField = //input[@data-ti='input']
xpath.hotelWhereListFirstElement = (//div[@data-ti='dropdown-item'])[1]
xpath.hotelWhenField = //*[@id="__next"]/div[2]/div/div/div[2]/div[3]/div/div[2]/div[1]/div[1]/div/label/input
xpath.hotelNextMonth = //button[@data-ti='calendar-month-header-next-button']
xpath.hotelChooseDate = //button[@data-ti='calendar-popper-footer-select-button']
xpath.hotelSelectGuests = //input[@data-ti='guests_input']
xpath.hotelDecreaseGuests = //button[@data-ti='minus_button']
xpath.hotelIncreaseGuests = //button[@data-ti='plus_button']
xpath.addChildButton = //button[@data-ti='add_child_button']
xpath.searchHotelButton = //button[@data-ti='submit-button']

xpath.airplanesButton = //*[@id="__next"]/div[2]/div/div/div[2]/div[2]/button[2]
xpath.airplanesFrom = (//input[@data-ti='input'])[1]
xpath.airplanesTo = (//input[@data-ti='input'])[2]
xpath.airplaintChooseWhenTo = //input[@data-ti='trip-dates']
xpath.airplanesChooseWhenBack = //input[@data-ti='trip-second-date']
xpath.airplanesPassagers = //div[@data-ti='passengers_input-root']
xpath.searchAirplanes = //button[@data-ti='submit-button']


xpath.fromField=//*[@id="__next"]/div[2]/div/div/div[2]/div[3]/div/div[1]/div[1]/div[1]/div/label/input