mainpage = https://www.tutu.ru/

xpath.calendarFirstDate = //input[contains(@data-ti, 'trip-date')]
xpath.calendarSecondDate = //input[contains(@data-ti, 'trip-second-date')]
xpath.calendarNextButton = //button[@data-ti='calendar-month-header-next-button']
xpath.calendarMonthDiv = //div[@data-ti='calendar-month-view']
xpath.calendarSelectButton = //button[@data-ti="calendar-popper-footer-select-button"]

xpath.locationFrom = (//div[contains(@data-ti, 'search')]//input[@data-ti='input'])[1]
xpath.locationTo = (//div[contains(@data-ti, 'search')]//input[@data-ti='input'])[2]
xpath.firstDurationFromList = (//div[@data-ti="dropdown-item"]//div[@data-ti="cell"]//span)[2]//span[text()='%s']

xpath.passengerMenu = //input[@data-ti='passengers_input' or @data-ti='guests_input']
xpath.passengerAdultPlus = //button[@data-ti='plus_button']
xpath.passengerAdultMinus = //button[@data-ti='minus_button']
xpath.passengerAdultCounterValue = //div[@data-ti='passengers_counter']//div[@data-ti='count']
xpath.passengerAddChildButton = //button[@data-ti='add_child_button']

xpath.searchButton = //button[@data-ti="submit-button"]